#!/usr/bin/env bash
# displaying content of the file /etc/psswd
file_path="/etc/passwd"

if [ -e "$file_path" ]; then
  
    while IFS=: read -r username _ userid _ homedir _; do
        echo "Username: $username"
        echo "User ID: $userid"
        echo "Home Directory: $homedir"
    done < "$file_path"
else
    echo "Error: $file_path does not exist."
fi
