#!/usr/bin/env bash
# displaying content of the file /etc/psswd
passwd_file="/etc/passwd"

if [ -e "$passwd_file" ]; then
  
    while IFS=: read -r username _ userid _ _ homedir _; do
        echo "Username: $username"
        echo "User ID: $userid"
        echo "Home Directory: $homedir"
    done < "$passwd_file"
else
    echo "Error: /etc/passwd file not found."
fi
