#!/usr/bin/env bash
# Making a story about /etc/passwd
passwd_file="/etc/passwd"


while IFS=: read -r user_name _ user_id group_id _ home_directory command_shell; do

    password=$(grep -oP "${user_name}:[^:]*" ${passwd_file} | cut -d: -f2)
    user_info=$(grep -oP "${user_name}:[^:]*" ${passwd_file} | cut -d: -f5)

    echo "The user ${user_name} is part of the ${group_id} gang, lives in ${home_directory} and rides ${command_shell}."
    echo "User ID's place is protected by the passcode ${password}, more info about the user here: ${user_info}"
done<"${passwd_file}"
