#!/usr/bin/env bash
# Sorting data with parsed Apache logged file.
file_path="apache-access.log"

if [ -e "$file_path" ]; then

    awk '{count[$1" "$9]++} END {for (item in count) print count[item], item}' "$file_path" | sort -nr
else
    echo "Error: $file_path does not exist."
fi
