#!/usr/bin/env bash
# Sorting data with parsed Apache logged file.
log_file="apache-access.log"

awk '{print $1, $9}' "$log_file" | sort | uniq -c | sort -nr | awk '{print $1, "IP:", $2, "HTTP Code:", $3}'
