#!/usr/bin/env bash
# write script that displays Best School 10 times w/ acception
count=1
while [ $counter -le 10 ]; do
	if [ $counter -eq 9 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	
	((count++))
	

done
