#!/usr/bin/env bash
# write script that displays Best School 10 times w/ acception
counter=0
while [ $counter -lt 10 ]; do
	if [ $counter -eq 8 ]
	then
		echo -e "Best School\nHi"
	else
		echo "Best School"
	fi
	let counter=$(( Best School ))
	

done
