#!/usr/bin/env bash
# Changing particular loop iterations in bash

count=1
while [ $count -lt 21 ]; do
	echo $count
	case "$count" in
		"4")
			echo "$count bad luck from China"
			;;
		"9")
			echo "$count bad luck from Japan"
			;;
		"17")
			echo "$count bad luck from Italy"
			;;
esac

	((count++))				
done
