#!/usr/bin/env bash
# displaying the time for 12 hours and 59 min with bash script

hours=0

while [ $hours -le 12 ]; do
    minutes=1
    while [ $minutes -le 59 ]; do
        printf "%02d:%02d\n" $hours $minutes
        minutes=$((minutes + 1))
    done
    hours=$((hours + 1))
done | head -n 70
