#!/usr/bin/env bash
# displaying the time for 12 hours and 59 min with bash script

hour=0

while [ $hour -le 12 ]; do
    minute=1

    while [ $minute -le 59 ]; do
        echo "$hour:$minute"
        ((minute++))
    done

    ((hour++))
done
